services:
#    my_app_user.example:
#        class: MyApp\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    fos_user.doctrine_registry:
        alias: doctrine
    redirect.after.login:
        class: MyApp\UserBundle\Redirection\AfterLoginRedirection
        arguments: ["@router"]